# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-activities}
  s.version = "3.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball", "Joel Duffin"]
  s.date = %q{2011-02-12}
  s.description = %q{Activity engine for the muck system.}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/muck/activities_controller.rb",
    "app/helpers/muck_activity_helper.rb",
    "app/models/activity_feed.rb",
    "app/views/activities/_activity_feed.erb",
    "app/views/activities/_activity_scripts.erb",
    "app/views/activities/_cached_activities.erb",
    "app/views/activities/_comment.erb",
    "app/views/activities/_comments.erb",
    "app/views/activities/_contribute.erb",
    "app/views/activities/_current_status.erb",
    "app/views/activities/_current_status_wrapper.erb",
    "app/views/activities/_status_update.erb",
    "app/views/activities/_template_filter.erb",
    "app/views/activities/create.js.erb",
    "app/views/activities/destroy.js.erb",
    "app/views/activity_templates/_generic.erb",
    "app/views/activity_templates/_status_update.erb",
    "config/locales/ar.yml",
    "config/locales/bg.yml",
    "config/locales/ca.yml",
    "config/locales/cs.yml",
    "config/locales/da.yml",
    "config/locales/de.yml",
    "config/locales/el.yml",
    "config/locales/en.yml",
    "config/locales/es.yml",
    "config/locales/et.yml",
    "config/locales/fa.yml",
    "config/locales/fi.yml",
    "config/locales/fr.yml",
    "config/locales/gl.yml",
    "config/locales/hi.yml",
    "config/locales/hr.yml",
    "config/locales/hu.yml",
    "config/locales/id.yml",
    "config/locales/it.yml",
    "config/locales/iw.yml",
    "config/locales/ja.yml",
    "config/locales/ko.yml",
    "config/locales/lt.yml",
    "config/locales/lv.yml",
    "config/locales/mt.yml",
    "config/locales/nl.yml",
    "config/locales/no.yml",
    "config/locales/pl.yml",
    "config/locales/pt-PT.yml",
    "config/locales/pt.yml",
    "config/locales/ro.yml",
    "config/locales/ru.yml",
    "config/locales/sk.yml",
    "config/locales/sl.yml",
    "config/locales/sq.yml",
    "config/locales/sr.yml",
    "config/locales/sv.yml",
    "config/locales/th.yml",
    "config/locales/tl.yml",
    "config/locales/tr.yml",
    "config/locales/uk.yml",
    "config/locales/vi.yml",
    "config/locales/zh-CN.yml",
    "config/locales/zh-TW.yml",
    "config/locales/zh.yml",
    "config/routes.rb",
    "db/migrate/20090402033319_add_muck_activities.rb",
    "db/migrate/20090730044139_add_comment_cache.rb",
    "db/migrate/20090818204527_add_activity_indexes.rb",
    "db/migrate/20090819030523_add_attachable_to_activities.rb",
    "lib/muck-activities.rb",
    "lib/muck-activities/config.rb",
    "lib/muck-activities/engine.rb",
    "lib/muck-activities/models/activity.rb",
    "lib/muck-activities/models/activity_consumer.rb",
    "lib/muck-activities/models/activity_item.rb",
    "lib/muck-activities/models/activity_source.rb",
    "lib/tasks/muck_activities.rake",
    "muck-activities.gemspec",
    "public/images/loading.gif",
    "public/javascripts/muck_activities.js",
    "public/stylesheets/muck-activities.css"
  ]
  s.homepage = %q{http://github.com/tatemae/muck-activities}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Activity engine for the muck system}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_runtime_dependency(%q<muck-comments>, [">= 0"])
    else
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<muck-comments>, [">= 0"])
    end
  else
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<muck-comments>, [">= 0"])
  end
end

